baseURL = 'https://example.com/'
languageCode = 'en-us'
title = 'Abhiram'

[params]
  author = 'Abhiram'
  role = 'Software Engineer'
  description = 'Building reliable systems and solving problems through code'
  email = 'abhiramvanand@gmail.com'
  github = 'AbhiramVAnand'
  linkedin = 'abhiramvanand'

[menu]
  [[menu.main]]
    name = 'Projects'
    url = '/projects/'
    weight = 1
  [[menu.main]]
    name = 'Writing'
    url = '/blog/'
    weight = 2
  [[menu.main]]
    name = 'About'
    url = '/about/'
    weight = 3
  [[menu.main]]
    name = 'Contact'
    url = '/contact/'
    weight = 4

[markup]
  [markup.highlight]
    style = 'monokailight'
    lineNos = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
